### ISSUE TITLE
Example for getting schematic_file_converter DOES NOT WORK!!!

### ISSUE THREAD

**Issue by tatzelbrumm** [faerietree/shell__coexisting_alternate_python_version#1]
pip install freetype and pip install PIL don't work.
## Output of ~/virtualpythonenvironment_python2.6/bin/pip install freetype

/home/cmaier/virtualpythonenvironment_python2.6/bin/pip run on Wed Dec 30 17:49:59 2015
Downloading/unpacking freetype

  Getting page https://pypi.python.org/simple/freetype/
  URLs to search for versions for freetype:
- https://pypi.python.org/simple/freetype/
  Analyzing links from page https://pypi.python.org/simple/freetype/
    Skipping link https://pypi.python.org/packages/2.4/F/Freetype/Freetype-Milestone1-py2.4-win32.egg#md5=a113164f1b9b9270078906d54243ca0e (from https://pypi.python.org/simple/freetype/); unknown archive format: .egg
  Could not find any downloads that satisfy the requirement freetype

No distributions at all found for freetype

Exception information:
Traceback (most recent call last):
  File "/home/cmaier/virtualpythonenvironment_python2.6/lib/python2.6/site-packages/pip-1.3.1-py2.6.egg/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/home/cmaier/virtualpythonenvironment_python2.6/lib/python2.6/site-packages/pip-1.3.1-py2.6.egg/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/cmaier/virtualpythonenvironment_python2.6/lib/python2.6/site-packages/pip-1.3.1-py2.6.egg/pip/req.py", line 1026, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/cmaier/virtualpythonenvironment_python2.6/lib/python2.6/site-packages/pip-1.3.1-py2.6.egg/pip/index.py", line 171, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for freetype
## Output of ~/virtualpythonenvironment_python2.6/bin/pip install PIL

bin/pip run on Wed Dec 30 17:35:10 2015
Downloading/unpacking PIL

  Getting page https://pypi.python.org/simple/PIL/
  URLs to search for versions for PIL:
- https://pypi.python.org/simple/PIL/
  Analyzing links from page https://pypi.python.org/simple/pil/
  Could not find any downloads that satisfy the requirement PIL

No distributions at all found for PIL

Exception information:
Traceback (most recent call last):
  File "/home/cmaier/virtualpythonenvironment_python2.6/lib/python2.6/site-packages/pip-1.3.1-py2.6.egg/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/home/cmaier/virtualpythonenvironment_python2.6/lib/python2.6/site-packages/pip-1.3.1-py2.6.egg/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/cmaier/virtualpythonenvironment_python2.6/lib/python2.6/site-packages/pip-1.3.1-py2.6.egg/pip/req.py", line 1026, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/cmaier/virtualpythonenvironment_python2.6/lib/python2.6/site-packages/pip-1.3.1-py2.6.egg/pip/index.py", line 171, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for PIL

**Comment by faerietree** [comment]
Can you provide the operating system version?

Seems to be pip problem -the freetype is not found for download ... did you try freecad-py? (This was why I cd into freecad-py in the example you quoted if I remember correctly.)

Software becomes incompatible to other software quickly.

This is why worlddevelopment figured the sophisticated development strategy we currently set up.
